### ISSUE TITLE
The bot stopped working 2 months ago!

### ISSUE THREAD

**Issue by C0D3D3V** [LucaVazz/DualisWatcher#4]
Maybe you can help :D

2018-10-03 12:48:16  INFO  {main}  --- main started ---------------------
2018-10-03 12:48:16  DEBUG  {main}  Loading config...
2018-10-03 12:48:16  DEBUG  {base}  Configuring Raven for host: https://sentry.io
2018-10-03 12:48:16  DEBUG  {main}  Checking for changes for the configured Dualis-Account....
2018-10-03 12:48:16  DEBUG  {dualis_service}  Fetching current Dualis State...
2018-10-03 12:48:16  ERROR  {main}  Traceback (most recent call last):
  File "/home/daniel/DualisWatcher/dualis_connector/dualis_service.py", line 55, in _fetch_state
    semesters = list_handler.fetch_semesters()
  File "/home/daniel/DualisWatcher/dualis_connector/results_handler.py", line 14, in fetch_semesters
    page = self.request_helper.get_ressource('COURSERESULTS')
  File "/home/daniel/DualisWatcher/dualis_connector/request_helper.py", line 49, in get_ressource
    return self._initial_parse(response)
  File "/home/daniel/DualisWatcher/dualis_connector/request_helper.py", line 104, in _initial_parse
    error_title, ' (' + error_description + ')' if (error_description != '') else ''
dualis_connector.request_helper.RequestRejectedError: The Dualis System rejected the Request. Details: Zugang verweigert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 141, in run_main
    results = dualis.fetch_and_check_state()
  File "/home/daniel/DualisWatcher/dualis_connector/dualis_service.py", line 87, in fetch_and_check_state
    results = self._fetch_state()
  File "/home/daniel/DualisWatcher/dualis_connector/dualis_service.py", line 62, in _fetch_state
    raise RuntimeError('Error while communicating with the Dualis System! (%s)' % (error))
RuntimeError: Error while communicating with the Dualis System! (The Dualis System rejected the Request. Details: Zugang verweigert)

2018-10-03 12:48:16  DEBUG  {base}  Sending message of length 2972 to https://sentry.io/api/301640/store/
2018-10-03 12:48:16  DEBUG  {main}  Exception-Handling completed. Exiting...

**Comment by C0D3D3V** [comment]
After a short research I believe that dualis now wants the 'cnsc' cookie in any case.
